-- SETTING UP SELF PORTRAITS OF AUTHORS

UPDATE AUTHOR A INNER JOIN
(
SELECT ID, AUTHOR_ID, TITLE FROM `ART` WHERE `TITLE` LIKE '%self-portrait%'
) B ON A.ID=B.AUTHOR_ID
SET A.FIMAGE=B.ID;


-- UPDATING FEATURE IMAGES OF CATEGORIES

UPDATE FORM A INNER JOIN
(
SELECT Y.ID, (SELECT ID FROM `ART` Z WHERE Z.FORM_ID=Y.ID ORDER BY RAND() LIMIT 1) AS FIMAGE FROM FORM Y GROUP BY Y.ID
) B ON A.ID=B.ID AND B.FIMAGE IS NOT NULL
SET A.FIMAGE=B.FIMAGE;

UPDATE LOCATION A INNER JOIN
(
SELECT Y.ID, (SELECT ID FROM `ART` Z WHERE Z.LOCATION_ID=Y.ID ORDER BY RAND() LIMIT 1) AS FIMAGE FROM LOCATION Y GROUP BY Y.ID
) B ON A.ID=B.ID AND B.FIMAGE IS NOT NULL
SET A.FIMAGE=B.FIMAGE;

UPDATE SCHOOL A INNER JOIN
(
SELECT Y.ID, (SELECT ID FROM `ART` Z WHERE Z.SCHOOL_ID=Y.ID ORDER BY RAND() LIMIT 1) AS FIMAGE FROM SCHOOL Y GROUP BY Y.ID
) B ON A.ID=B.ID AND B.FIMAGE IS NOT NULL
SET A.FIMAGE=B.FIMAGE;

UPDATE TIMEFRAME A INNER JOIN
(
SELECT Y.ID, (SELECT ID FROM `ART` Z WHERE Z.TIMEFRAME_ID=Y.ID ORDER BY RAND() LIMIT 1) AS FIMAGE FROM TIMEFRAME Y GROUP BY Y.ID
) B ON A.ID=B.ID AND B.FIMAGE IS NOT NULL
SET A.FIMAGE=B.FIMAGE;

UPDATE TYPE A INNER JOIN
(
SELECT Y.ID, (SELECT ID FROM `ART` Z WHERE Z.TYPE_ID=Y.ID ORDER BY RAND() LIMIT 1) AS FIMAGE FROM TYPE Y GROUP BY Y.ID
) B ON A.ID=B.ID AND B.FIMAGE IS NOT NULL
SET A.FIMAGE=B.FIMAGE;


-- QUERY TO GET THE GROUPED VALUES OF CATEGORIES,

SELECT
    AU.ID, AU.AUTHOR, AU.BORN_DIED, 
    COALESCE(AR.CNT, 0) AS COUNT, 

    AR.FORM,
    AR.SCHOOL,
    AR.LOCATION,
    AR.TIMEFRAME,
    AR.TYPE

FROM AUTHOR AU
LEFT JOIN
(
    SELECT AUTHOR_ID, COUNT(ID) AS CNT, 

    GROUP_CONCAT(DISTINCT FORM  SEPARATOR '#') as 'FORM',
    GROUP_CONCAT(DISTINCT SCHOOL SEPARATOR '#') as 'SCHOOL',
    GROUP_CONCAT(DISTINCT LOCATION SEPARATOR '#') as 'LOCATION',
    GROUP_CONCAT(DISTINCT TIMEFRAME SEPARATOR '#') as 'TIMEFRAME',
    GROUP_CONCAT(DISTINCT TYPE SEPARATOR '#') as 'TYPE'
    
    FROM ARTDATA
    GROUP BY AUTHOR_ID
) AR
    ON AU.ID = AR.AUTHOR_ID
WHERE AR.CNT > 0
ORDER BY AU.ID ASC
